# Test
steps:
- id: 'Build image'
  name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/$PROJECT_ID/mock-service-1
  - --cache=true
  - --dockerfile=/workspace/$_SERVICE_NAME/app/Dockerfile