# Test
steps:
- name: gcr.io/cloud-builders/git
  args: ['fetch', '--unshallow']
- name: 'gcr.io/cloud-builders/git'
  id: 'Detect changed services'
  entrypoint: "bash"
  args: ["-c" ,'./detect_changes.sh']
  env:
  - 'COMMIT_SHA=$COMMIT_SHA'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud config set builds/use_kaniko True
      while IFS= read -r release_candidate; do
        gcloud builds submit $release_candidate --async --tag gcr.io/$PROJECT_ID/$(echo $release_candidate | rev | cut -d "/" -f2 | rev)
      done < release_candidates.txt

# - name: 'gcr.io/cloud-builders/docker'
#   entrypoint: 'bash'
#   args:
#     - '-c'
#     - |
#       while IFS= read -r release_candidate; do
#         docker build -t gcr.io/$PROJECT_ID/$(echo $release_candidate | rev | cut -d "/" -f2 | rev) -f $release_candidate .
#       done < release_candidates.txt


# - id: 'Build image'
#   name: 'gcr.io/kaniko-project/executor:latest'
#   args:
#   - --destination=gcr.io/$PROJECT_ID/mock-service-1
#   - --cache=true
#   - --dockerfile=/workspace/$_SERVICE_NAME/app/Dockerfile